swagger: '2.0'
info:
  title: CP4I Test-dJd56X
  version: 0.0.1
basePath: /dJd56X
paths:
  '/testmsg/{id}':
    get:
      tags:
        - testmsg
      summary: 'Find a model instance by {{id}} from the data source.'
      operationId: testmsg.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/testmsg'
      deprecated: false
definitions:
  x-any:
    properties: {}
  testmsg:
    description: ''
    properties:
      msgid:
        type: string
      msgData:
        type: string
    required:
      - msgid
    additionalProperties: false
schemes:
  - https
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - application/xml
  - text/xml
produces:
  - application/json
  - application/xml
  - text/xml
  - application/javascript
  - text/javascript
x-ibm-configuration:
  assembly:
    execute:
      - set-variable:
          actions:
            - set: message.headers.Authorization
              value: >-
                Basic
                YXBwY29udXNlcjAxOjgyNDg2M2JlLTg5NTctNDQ0Yi05N2IzLTNhNmVkYmI0N2NmMA==
      - invoke:
          target-url: >-
            https://apis-5.appconnect.ibmcloud.com$(request.path)$(request.search)
          verb: keep
  cors:
    enabled: true
securityDefinitions:
  client_id:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
    x-key-type: clientId
security:
  - client_id: []
tags:
  - name: testmsg
    description: ''
